### PR TITLE
Auth docs js fix

### PR DESCRIPTION
**Pull request by srobertson421**
Changed the docs for JS signup call to include username/email object as first argument. Previous example resulted in 400 validation errors.

### CODE REVIEW

**Comment by tasn** [comment]
The doc fix looks great, but you accidentally also added `package-lock.json`. Could you please remove it so I can merge this? Thanks!

**Comment by srobertson421** [comment]
Ah crap, I see that. Yep I'm on it!

**Comment by srobertson421** [comment]
@tasn removed!

**Comment by tasn** [comment]
Great, thanks!

**Pull request merged**
